# Generated by Django 5.0.7 on 2024-07-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='position',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
