# Generated by Django 5.0.7 on 2024-07-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginger', '0002_alter_employeedata_age_alter_employeedata_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
