# Generated by Django 5.0.7 on 2024-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginger', '0003_employeedata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='img',
            field=models.ImageField(height_field='100px', null=True, upload_to='img', width_field='100px'),
        ),
    ]
