# Generated by Django 5.0.7 on 2024-07-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginger', '0004_employeedata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
