# Generated by Django 5.0.7 on 2024-07-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wow_model',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
