# Generated by Django 5.1.4 on 2024-12-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_wow_model_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='wow_model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
