# Generated by Django 5.1.4 on 2024-12-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_wow_model_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wow_model',
            name='description',
        ),
    ]
