# Generated by Django 5.1.4 on 2024-12-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_wow_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wow_model',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
