# Generated by Django 5.0.7 on 2024-08-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
