# Generated by Django 5.0.7 on 2024-08-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productdata_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='productdata',
            name='category',
        ),
        migrations.AddField(
            model_name='productdata',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
