# Generated by Django 5.0.7 on 2024-08-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_remove_productdata_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
