# Generated by Django 5.0.7 on 2024-08-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_productdata_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='category',
            field=models.CharField(choices=[('Mobile', 'mobile'), ('Headset', 'headset'), ('Watch', 'watch'), ('Battery', 'battery'), ('Case', 'case'), ('Electronics', 'electronics')], default='Electronics', max_length=50),
        ),
    ]
