# Generated by Django 5.1 on 2024-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
