# Generated by Django 5.1 on 2024-09-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_taskmodel_task_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=50)),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taskmodel')),
            ],
        ),
    ]
