# Generated by Django 5.1 on 2024-09-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_personmodel_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidneyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personmodel',
            name='kidney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.kidneymodel'),
        ),
    ]
