# Generated by Django 5.1 on 2024-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_kidneymodel_personmodel_kidney'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
