# Generated by Django 5.0.7 on 2024-07-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='blogId',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='blogId',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
